[package]
name = "cayasde/profilestore-wrapper"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
include = ["src", "default.project.json", "wally.toml"]

[dependencies]
promise = "howmanysmall/typed-promise@4.0.6"
