[package]
name = "cayasde/profilestore-wrapper"
version = "0.1.9"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "howmanysmall/typed-promise@4.0.6"
